apiVersion: v1
kind: Service
metadata:
  name: external-lb
  namespace: default
spec:
  type: LoadBalancer 
  ports:
    - name: tak-cot-port 
      port: 8089
      protocol: TCP
      targetPort: '8089-port'
    - name: tak-tls-port 
      port: 8443
      protocol: TCP
      targetPort: '8443-port'
  selector:
    lbtype: external