apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-tak.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: tak-database
  name: tak-database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tak-database
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-tak.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        #io.kompose.network/takserver: "true"
        io.kompose.service: tak-database
    spec:
      containers:
        - image: stormcloud-takserver-db-k8s
          imagePullPolicy: Never
          name: tak-database
          ports:
            - containerPort: 5432
          resources: {}
          tty: true
      hostname: tak-database
      restartPolicy: Always
status: {}
