apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-tak.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: takserver
  name: takserver
  namespace: default
spec:
  #type: LoadBalancer
  ports:
    - name: 8443-port
      port: 8443
      targetPort: 8443
    - name: "8446"
      port: 8446
      targetPort: 8446
    - name: 8089-port
      port: 8089
      targetPort: 8089
    - name: "8444"
      port: 8444
      targetPort: 8444
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: takserver
status:
  loadBalancer: {}
