#FROM openjdk:11-jdk-bullseye
FROM mcr.microsoft.com/openjdk/jdk:11-ubuntu
RUN apt update && \
    apt-get install emacs-nox net-tools netcat vim -y
ENV CITY=London
ENV ORGANIZATION=Microsoft
ENV ORGANIZATIONAL_UNIT=CSE
ENV STATE=London
ENV USER_COUNT=1
ENV ADMINS_COUNT=1

RUN useradd -g 0 -u 1001 tak \
    && usermod -a -G root tak \
    && mkdir /opt/configurator

USER tak:0

COPY --chown=tak:0 /tak-server/tak/ /opt/tak
COPY --chown=tak:0 configureInDocker.sh /opt/tak
COPY --chown=tak:0 configurator.sh /opt/configurator
COPY --chown=tak:0 CoreConfig.xml /opt/tak

RUN chmod u=rwx /opt/tak \
	&& find /opt/tak/ -type f -name "*.sh" -exec chmod u=rwx {} \; \
	&& find /opt/configurator/ -type f -name "*.sh" -exec chmod u=rwx {} \;


ENTRYPOINT ["/bin/bash", "-c", "/opt/tak/configureInDocker.sh init"]
